<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-20T11:27:02 IST" name="Default suite" finished-at="2024-03-20T11:27:04 IST" duration-ms="2377">
    <groups>
    </groups>
    <test started-at="2024-03-20T11:27:02 IST" name="Default test" finished-at="2024-03-20T11:27:04 IST" duration-ms="2377">
      <class name="HomeLyf.test.QDTAS_LoginTestCase">
        <test-method is-config="true" signature="QDTAS_data()[pri:0, instance:HomeLyf.test.QDTAS_LoginTestCase@72035809]" started-at="2024-03-20T11:27:02 IST" name="QDTAS_data" finished-at="2024-03-20T11:27:02 IST" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QDTAS_data -->
        <test-method signature="qdtasUpdateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:6, instance:HomeLyf.test.QDTAS_LoginTestCase@72035809]" started-at="2024-03-20T11:27:02 IST" name="qdtasUpdateUser" data-provider="qdtasUpdateUserDetails" finished-at="2024-03-20T11:27:04 IST" duration-ms="2301" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void HomeLyf.test.QDTAS_LoginTestCase.qdtasUpdateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: qdtasUpdateUser([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7, java.lang.String arg8, java.lang.String arg9, java.lang.String arg10, java.lang.String arg11, java.lang.String arg12, java.lang.String arg13])
Arguments: [(java.lang.String) mayivec121@irnini.com,(java.lang.String) Bebo@123,(java.lang.String) om,(java.lang.String) shiv,(java.lang.String) singal,(java.lang.String) Male,(java.lang.String) 2,(java.lang.String) QA,(java.lang.String) 1234567892,(java.lang.String) ManualTester,(java.lang.String) 1998-07-18,(java.lang.String) 2018-08-18,(java.lang.String) Pune]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void HomeLyf.test.QDTAS_LoginTestCase.qdtasUpdateUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: qdtasUpdateUser([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7, java.lang.String arg8, java.lang.String arg9, java.lang.String arg10, java.lang.String arg11, java.lang.String arg12, java.lang.String arg13])
Arguments: [(java.lang.String) mayivec121@irnini.com,(java.lang.String) Bebo@123,(java.lang.String) om,(java.lang.String) shiv,(java.lang.String) singal,(java.lang.String) Male,(java.lang.String) 2,(java.lang.String) QA,(java.lang.String) 1234567892,(java.lang.String) ManualTester,(java.lang.String) 1998-07-18,(java.lang.String) 2018-08-18,(java.lang.String) Pune]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- qdtasUpdateUser -->
      </class> <!-- HomeLyf.test.QDTAS_LoginTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
